### ISSUE TITLE
Can not Control 

### ISSUE THREAD

**Issue by coderykw** [takatost/homebridge-mi-ac-partner#3]
V1  hk is yes but. Can’t control

**Comment by mulua6** [comment]
I can see the ac partner in my home app but can't control

**Comment by takatost** [comment]
Yes, i knew this problem, I'm trying to develop a new version of the homebridge plugin to select brand and preset in config.

**Comment by takatost** [comment]
The same to https://github.com/takatost/homebridge-mi-ac-partner/issues/2
